# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b47174799afba3c073d571e1e0e1973cc31efd2e75a5bd5cba5cafbae3bccd270f4b9e7433bfd0fd1d768e6dc9b7459b696f43b357a25f68e7e15a032a8293d2

test:
  secret_key_base: a02802c49f62c542d40f73980da97a7058ceaf7f7f34c8bfdbf82c7797c53eec433ebdb2de62504f150e5a8fd830d0c65b8563b1a4ad606afb1f4eb5b157ab9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
